### ISSUE TITLE
kv backup -> UnicodeEncodeError: 'ascii' codec can't encode character u'\u01a7'

### ISSUE THREAD

**Issue by gdhbashton** [gmr/consulate#21] opened 2015-01-28 09:25 UTC
I get $title error with both the 0.2.0 from `pip install consulate` and also with current Git of consulate + PR #18 when I try to backup the KV store

I do have international non-ASCII chars in the KV store and consulate should definitely be able to backup + restore these.

Cheers,
Gavin.

**Comment by sielaq** [comment] 2015-01-28 13:04
I think you have applite one patch too much - from non mergeed.
my fault in patch is str() - I was looking for a place where to fix the backup/restore problem and provided anoter one - just easiest solution is to replace 
str(row[3]) with row[3].encode('utf-8')  - this is the moment when mapping have to be done
in consulate/cli.py line 101 I will fix my proposal  
@gmr would be good to have some unittests for special charcters in UTF-8 encoding

**Comment by sielaq** [comment] 2015-01-28 13:20
patch fixed. This can be closed since it was not even in master.

**Comment by gmr** [comment] 2015-03-13 19:14
Confirmed this behavior in 0.3.0.

**Comment by gmr** [comment] 2015-03-13 21:42
This will be fixed in 0.4.0 which I plan on pushing out shortly.

**Closed by gmr** 2015-03-13 21:42 UTC
